title: Documentation website for node-red-contrib-infocache
author: Julian Knight (Totally Information)
description: > 
  node-red-contrib-infocache is a full featured caching node for Node-RED.
  It is also engineered to link into the control messages from node-red-contrib-uibuilder allowing easy provision and control of a data cache for your web apps.

theme: minima

# social links
twitter_username: knightnet
github_username:  TotallyInformation

show_excerpts: true # set to false to remove excerpts on the homepage